# Generated by Django 3.0 on 2020-09-14 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Autotest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.BooleanField(null=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_hisopado', models.DateField(default=True)),
                ('id_autotest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autotest.Autotest')),
            ],
        ),
    ]
