# Generated by Django 3.0 on 2020-09-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('id_autotest', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('resultado', models.BooleanField(null=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_hisopado', models.DateField(default=True)),
            ],
        ),
    ]
