# Generated by Django 3.0 on 2020-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200904_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre localidad')),
                ('cant_habitantes', models.IntegerField(verbose_name='cantidad de habitantes')),
            ],
        ),
    ]
