# Generated by Django 3.0 on 2020-09-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.TextField(default=True, max_length=70),
        ),
    ]
