# Generated by Django 3.0 on 2020-09-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autotest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tosSeca', models.BooleanField(null=True, verbose_name='Tos seca')),
                ('fiebre', models.BooleanField(null=True, verbose_name='Fiebre')),
                ('dolorCabeza', models.BooleanField(null=True, verbose_name='Dolor de cabeza')),
                ('dolorCorporal', models.BooleanField(null=True, verbose_name='Dolor corporal')),
                ('contactoConPositivo', models.BooleanField(null=True, verbose_name='Contacto con una persona covid positivo')),
                ('dificultadRespiratoria', models.BooleanField(null=True, verbose_name='Dificultad respiratoria')),
                ('mucosidad', models.BooleanField(null=True, verbose_name='Mucosidad')),
                ('enfermedad', models.BooleanField(null=True, verbose_name='Enfermedad preexistente')),
                ('vomitos', models.BooleanField(null=True, verbose_name='Vomitos o nauseas')),
                ('diarrea', models.BooleanField(null=True, verbose_name='Diarrea')),
                ('dolordeGarganta', models.BooleanField(null=True, verbose_name='Dolor de garganta')),
                ('alteracionGustoOfalto', models.BooleanField(null=True, verbose_name='Alteración gusto/olfato')),
                ('texto', models.TextField(max_length=200, null=True, verbose_name='Sintomas/Información que desee agregar')),
                ('corresponde_hisopado', models.BooleanField(null=True)),
            ],
        ),
    ]
