# Generated by Django 3.0 on 2020-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autotest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tosSeca', models.BooleanField()),
                ('fiebre', models.BooleanField()),
                ('dolorCabeza', models.BooleanField()),
                ('dolorCorporal', models.BooleanField()),
                ('contactoConPositivo', models.BooleanField()),
                ('dificultadRespiratoria', models.BooleanField()),
                ('mucosidad', models.BooleanField()),
            ],
        ),
    ]
