# Generated by Django 3.0 on 2020-09-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autotest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tosSeca', models.BooleanField(null=True, verbose_name='Tos seca')),
                ('fiebre', models.BooleanField(null=True, verbose_name='Fiebre')),
                ('dolordeGarganta', models.BooleanField(null=True, verbose_name='Dolor de garganta')),
                ('dolorCorporal', models.BooleanField(null=True, verbose_name='Dolor corporal')),
                ('contactoConPositivo', models.BooleanField(null=True, verbose_name='Contacto con una persona covid positivo')),
                ('dolorCabeza', models.BooleanField(null=True, verbose_name='Dolor de cabeza')),
                ('dificultadRespiratoria', models.BooleanField(null=True, verbose_name='Dificultad respiratoria')),
                ('alteracionGustoOfalto', models.BooleanField(null=True, verbose_name='Alteración gusto/olfato')),
                ('mucosidad', models.BooleanField(null=True, verbose_name='Mucosidad')),
                ('enfermedad', models.BooleanField(null=True, verbose_name='Enfermedad preexistente')),
                ('vomitos', models.BooleanField(null=True, verbose_name='Vomitos o nauseas')),
                ('diarrea', models.BooleanField(null=True, verbose_name='Diarrea')),
                ('texto', models.TextField(max_length=200, null=True, verbose_name='Sintomas/Información que desee agregar')),
                ('corresponde_hisopado', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.BooleanField(null=True)),
                ('estado', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateField()),
                ('fecha_hisopado', models.DateField(default=True)),
                ('id_autotest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autotest.Autotest')),
            ],
        ),
    ]
