# Generated by Django 3.0 on 2020-09-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotest',
            name='alteracionGustoOfalto',
            field=models.BooleanField(null=True, verbose_name='Alteración gusto/olfato'),
        ),
        migrations.AddField(
            model_name='autotest',
            name='diarrea',
            field=models.BooleanField(null=True, verbose_name='Diarrea'),
        ),
        migrations.AddField(
            model_name='autotest',
            name='dolordeGarganta',
            field=models.BooleanField(null=True, verbose_name='Dolor de garganta'),
        ),
        migrations.AddField(
            model_name='autotest',
            name='enfermedad',
            field=models.BooleanField(null=True, verbose_name='Enfermedad preexistente'),
        ),
        migrations.AddField(
            model_name='autotest',
            name='texto',
            field=models.TextField(max_length=200, null=True, verbose_name='Sintomas/Información que desee agregar'),
        ),
        migrations.AddField(
            model_name='autotest',
            name='vomitos',
            field=models.BooleanField(null=True, verbose_name='Vomitos o nauseas'),
        ),
        migrations.AlterField(
            model_name='autotest',
            name='contactoConPositivo',
            field=models.BooleanField(null=True, verbose_name='Contacto con una persona covid positivo'),
        ),
        migrations.AlterField(
            model_name='autotest',
            name='dificultadRespiratoria',
            field=models.BooleanField(null=True, verbose_name='Dificultad respiratoria'),
        ),
        migrations.AlterField(
            model_name='autotest',
            name='dolorCabeza',
            field=models.BooleanField(null=True, verbose_name='Dolor de cabeza'),
        ),
        migrations.AlterField(
            model_name='autotest',
            name='dolorCorporal',
            field=models.BooleanField(null=True, verbose_name='Dolor corporal'),
        ),
        migrations.AlterField(
            model_name='autotest',
            name='fiebre',
            field=models.BooleanField(null=True, verbose_name='Fiebre'),
        ),
        migrations.AlterField(
            model_name='autotest',
            name='mucosidad',
            field=models.BooleanField(null=True, verbose_name='Mucosidad'),
        ),
        migrations.AlterField(
            model_name='autotest',
            name='tosSeca',
            field=models.BooleanField(null=True, verbose_name='Tos seca'),
        ),
    ]
