# Generated by Django 3.0 on 2020-09-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autotest', '0002_auto_20200904_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotest',
            name='corresponde_hisopado',
            field=models.BooleanField(null=True),
        ),
    ]
